networks:
  dmz-net:
  int-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:

  # Spring Boot 웹 애플리케이션
  web-server:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: whair-web
    environment:
      # 데이터베이스 연결 설정
      DB_URL: jdbc:postgresql://db-server:5432/wh_air
      DB_USERNAME: wh_manager
      DB_PASSWORD: password
      
      # Spring Boot 설정
      SPRING_PROFILES_ACTIVE: docker
      
      # JVM 설정 (Spring Boot 웹 애플리케이션용)
      # -Xmx512m: 최대 힙 메모리 512MB (이 값 초과시 OutOfMemoryError)
      # -Xms256m: 초기 힙 메모리 256MB (시작시 할당, 필요시 최대 512MB까지 증가)
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "8080:8080"
    depends_on:
      db-server:
        condition: service_healthy
    networks:
      - dmz-net
      - int-net
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # PostgreSQL 14.15 데이터베이스 (커스텀 Dockerfile 사용)
  db-server:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    extra_hosts:
      - "admin-server:172.30.0.4"
    container_name: whair-db
    environment:
      POSTGRES_DB: wh_air
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      int-net:
        ipv4_address: 172.30.0.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wh_manager -d wh_air"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 관리자 서버 (내부망 전용 JSP + Tomcat)
  admin-server:
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
    container_name: whair-admin
    # 개발용 임시 포트 매핑 (운영 시 제거 필요)
    ports:
      - "8081:8080"
    depends_on:
      - db-server
    networks:
      int-net:
        ipv4_address: 172.30.0.4
    restart: unless-stopped

# 볼륨 정의
volumes:
  postgres_data:
    driver: local
