networks:
  ext-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16
  int-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:

  nginx:
    image: nginx:latest
    container_name: whair-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-server-1
      - web-server-2
    networks:
      ext-net:
        ipv4_address: 172.40.0.2
    restart: unless-stopped

  web-server-1:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: whair-web-1
    environment:
      DB_URL: jdbc:postgresql://db-server:5432/wh_air
      DB_USERNAME: wh_manager
      DB_PASSWORD: password!
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Xmx512m -Xms256m"
    depends_on:
      db-server:
        condition: service_healthy
    networks:
      ext-net:
        ipv4_address: 172.40.0.3
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    # 포트 노출 없음 (Nginx가 프록시)
    ports: []

  web-server-2:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: whair-web-2
    environment:
      DB_URL: jdbc:postgresql://db-server:5432/wh_air
      DB_USERNAME: wh_manager
      DB_PASSWORD: password!
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Xmx512m -Xms256m"
    depends_on:
      db-server:
        condition: service_healthy
    networks:
      ext-net:
        ipv4_address: 172.40.0.4
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    ports: []

  db-server:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    extra_hosts:
      - "admin-server:172.30.0.4"
    container_name: whair-db
    environment:
      POSTGRES_DB: wh_air
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      ext-net:
        ipv4_address: 172.40.0.5
      int-net:
        ipv4_address: 172.30.0.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wh_manager -d wh_air"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  admin-server:
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
    container_name: whair-admin
    environment:
      DB_HOST: db-server
      DB_PORT: 5432
      DB_NAME: wh_air
      DB_USER: wh_admin
      DB_PASSWORD: !ADpasswd@@
    depends_on:
      - db-server
    networks:
      int-net:
        ipv4_address: 172.30.0.4
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
